minimum_pre_commit_version: "4.0.0"
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: python -m ruff check --fix
        language: system
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff format
        entry: python -m ruff format
        language: system
        types_or: [python, pyi]

      - id: validate-editorconfig
        name: validate editorconfig syntax
        entry: python -c "import configparser, pathlib, sys; parser = configparser.ConfigParser(interpolation=None); [parser.read_string('[__root__]\n' + pathlib.Path(p).read_text(encoding='utf-8'), source=p) for p in sys.argv[1:]]"
        language: system
        files: ^\.editorconfig$
