urls:
  base: "https://www.akakce.com"
  search: "https://www.google.com"

browser:
  headless: false
  page_load_timeout: 45
  implicit_wait: 5
  captcha_auto_click: false
  reconnect_time: 6
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
  user_data_dir: ".browser_profile"
  profile_name: "Profile 1"
